package LanguageMps33634.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new Child_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new Macro_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new Root_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }



  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x11bf32844aec417cL, 0x98dfed1caa7260bcL, 0x52a5e623b92b0d48L), MetaIdFactory.conceptId(0x11bf32844aec417cL, 0x98dfed1caa7260bcL, 0x6d97cb85c70cbb1bL), MetaIdFactory.conceptId(0x11bf32844aec417cL, 0x98dfed1caa7260bcL, 0x52a5e623b92b0d47L)).seal();
}
