package LanguageMps33634.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Child = 0;
  public static final int Macro = 1;
  public static final int Root = 2;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x11bf32844aec417cL, 0x98dfed1caa7260bcL);
    builder.put(0x52a5e623b92b0d48L, Child);
    builder.put(0x6d97cb85c70cbb1bL, Macro);
    builder.put(0x52a5e623b92b0d47L, Root);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
